statusmessages = [
    "Ev.io | Type /help or !help",
    "Mine-craft.io | Type /help or !help",
    "Krunker.io | Type /help or !help",
    "I'll have 2 number 9's...",
    "You're finally awake!",
    "Why not Ziodberg?",
    "💀",
    "how very forgettable",
    "Who lives in a pineapple - nobody asked.",
    "Same thing everyday.",
    "Legalize nuclear bombs",
    "dead",
    "dark arts",
    "imaskingyourmom",
    "imaskingyourmom",
    "with fire",
    "never gonna-",
    "im gonna let you down",
    "gama did it not me",
    "🗿",
    "please no more lag",
    "ggs send trades",
    "ggs send kr",
    "why am i doing this now",
    "rage quiting",
    "richclub's with his 0$ networth",
    "imagine coding *crys*",
    "'get good'- random krunker player",
    "I'm the badgu- wait wdym your suing me",
    "I'm the Scatman!",
    "my opinion... io",
    "ggs send pic",
    "i... need... more... nft's... NOW",
    "just farm them",
    "back in 5 mins if not read this again",
    "Contractually bound by SOL",
    "S'that a Wolfmann reference?",
    "no uploads!??!!?",
    "no nft's!?!?!?",
    "down goes xborg",
    "tell forgeablesum",
    "thank you for calling Microsoft support",
    "i need 10k worth of google play cards",
    "sir that'll be 6 dollars",
    "im not lazy just on energy saving mode",
    "Free of charge... Until I shut this bot down and make another one. dont try me",
    "Build a cool, useful app and we'll even help you promote it. Message ForgeableSum#1514 in Discord if you have something cool to show.",
    "google it... oh you dont know how to use google well then just google it",
    "google how to get a life wikihow",
    "@everyone hi",
    "It’s so simple to be wise. Just think of something stupid to say and then don’t say it",
    "just pay someone to do it for you",
    "pclient back when!??!",
    "Kick da baby",
    "yeet the baby",
    "https://cdn.discordapp.com/attachments/929463046412312616/1100142224802582548/ragymlgb46ra1.mp4",
    "https://cdn.discordapp.com/attachments/972952855210238015/1124542520018346154/how_to_get_bitches.mp3",
    "no no wait another round trust me im good its just lag",
    "I was born at a young age",
    "forgettable um forget much??",
    "Forged with the finest homeless people.",
    " ™™ ",
    "forged in fire if forge fired his staff",
    "Ask ChatPP",
    "fuck off java",
    "oh you wanna know how to code PFT",
    "What's a class?",
    "not defind: end me",
    "syntax error: PLEASE WORK IM BEGGING YOU",
    "growing the tree",
    "Guest_3: you are all shit",
    "I have a dream…. A dream one day Shrimp are no longer offended",
    "It’s a shrimple formula",
    "Not so shrimple now",
    "It’s as shrimple as that",
    "thanks gama",
    "Aurum Potestas Est. - NOVA",
    "couldn't be possible without sigmadraconisiv",
    "add your own status by using /subbmitstatus",
    "what will be your status be? subbmit by using /subbmitstatus",
    "Im bicboiii",
]
